version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3300:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:


  #docker-compose up -d

